name: "\U0001F41B Bug report"
description: "When something isn't working as expected or documented"
title: ""
labels: ["kind/bug", "needs-triage"]
issue_body: true
body:
- type: markdown
  attributes:
    value: "Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html."
- type: textarea
  attributes:
    label: Terraform version
    description: |
      Run `terraform -v` to show the version of Terraform and providers you are 
      using. If you are not running the latest version of Terraform or the 
      providers, please upgrade because your issue may have already been fixed.
  validations:
    required: true
- type: textarea
  attributes:
    label: Affected resource(s)
    description: |
      Please list the resources as a list, for example:
      - opc_instance
      - opc_storage_volume

      If this issue appears to affect multiple resources, it may be an issue with
      Terraform's core, so please mention this.
  validations:
    required: true
- type: textarea
  attributes:
    label: Terraform configuration files
    value: |
      ```hcl
      ...
      ```
  validations:
    required: true
- type: textarea
  attributes:
    label: Debug output
    description: The output provided from prepending `TF_LOG=DEBUG` to your Terraform apply or plan.
  validations:
    required: false
- type: textarea
  attributes:
    label: Panic output
    description: Output from a crash or Go panic.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected output
    description: What did you expect to happen?
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual output
    description: What actually happened?
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: How can your issue be replicated?
    placeholder: |
      1. ...
      2. ...
      3. ...
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional factoids
    description: Is there any other important information you'd like to share?
  validations:
    required: false
- type: textarea
  attributes:
    label: References
    description: Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? 
  validations:
    required: false
