name: Acceptance Tests

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      CLOUDFLARE_ACCOUNT_ID: f037e56e89293a057740de681ac9abbe
      CLOUDFLARE_ALT_DOMAIN: terraform2.cfapi.net
      CLOUDFLARE_ALT_ZONE_ID: b72110c08e3382597095c29ba7e661ea
      CLOUDFLARE_DOMAIN: terraform.cfapi.net
      CLOUDFLARE_EMAIL: terraform-acceptance-test@cfapi.net
      CLOUDFLARE_ZONE_ID: 0da42c8d2132a9ddaf714f9e7c920711

      CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_LOGPUSH_OWNERSHIP_TOKEN: ${{ secrets.CLOUDFLARE_LOGPUSH_OWNERSHIP_TOKEN }}
      CLOUDFLARE_API_USER_SERVICE_KEY: ${{ secrets.CLOUDFLARE_API_USER_SERVICE_KEY }}

    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Pre-Sweeper
      run: go test ./cloudflare -v -sweep="1"

    - name: Run acceptance tests
      run: make testacc

    - name: Post-Sweeper
      if: ${{ always() }}
      run: go test ./cloudflare -v -sweep="1"
