name: Acceptance Tests

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      CLOUDFLARE_ACCOUNT_ID: f037e56e89293a057740de681ac9abbe
      CLOUDFLARE_ALT_DOMAIN: terraform2.cfapi.net
      CLOUDFLARE_ALT_ZONE_ID: b72110c08e3382597095c29ba7e661ea
      CLOUDFLARE_DOMAIN: terraform.cfapi.net
      CLOUDFLARE_EMAIL: terraform-acceptance-test@cfapi.net
      CLOUDFLARE_ZONE_ID: 0da42c8d2132a9ddaf714f9e7c920711
      CLOUDFLARE_MUTUAL_TLS_CERTIFICATE: "-----BEGIN CERTIFICATE-----\nMIIF2DCCA8CgAwIBAgIUP30oKJCqADPHOAIcaWRKhaPohnkwDQYJKoZIhvcNAQEN\nBQAwgYMxCzAJBgNVBAYTAlVTMQ4wDAYDVQQIEwVUZXhhczEPMA0GA1UEBxMGQXVz\ndGluMRcwFQYDVQQKEw5BY2Nlc3MgVGVzdGluZzELMAkGA1UECxMCVFgxLTArBgNV\nBAMTJFRlcnJhZm9ybSBQcm92aWRlciBBY2Nlc3MgVGVzdGluZyBDQTAeFw0yMTAz\nMTEwMDIwMDBaFw0yNjAzMTAwMDIwMDBaMIGDMQswCQYDVQQGEwJVUzEOMAwGA1UE\nCBMFVGV4YXMxDzANBgNVBAcTBkF1c3RpbjEXMBUGA1UEChMOQWNjZXNzIFRlc3Rp\nbmcxCzAJBgNVBAsTAlRYMS0wKwYDVQQDEyRUZXJyYWZvcm0gUHJvdmlkZXIgQWNj\nZXNzIFRlc3RpbmcgQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDH\n5ReqqDdkFRyVp1WL9TM1ITZIBdGvDX9fxaEuwWTrGyvlZ//yZm81QFCyKuoGDemQ\nNSQQBMxEPTZUw0LLn8ZE4jKdqmGxVQCu3iaiMOXcSYrreiqhsek5Z7p71L5wx3Mk\nfEsz8mkS0EPq+6XBkFIYyKzZW6CwqzA5KHD5Ct1DchCG4Z/ijbK9F9Wbo10AyJtG\n/yDxifjvh8aRnSDPEKlki80zvtKz/Hfts1HBS/aXmF/SVmxNlOUsDXnulT+8rFVl\n3JZpYC+tso3t9uRd+fOgfP34Y8gysJK7MCM2rVNKczVSBw6R/pjVpbH1yZbTAOoA\n5IdhvjDXFj0Mt4T9fJgnqBKxhoYsXInN+YmCimFF99BTtuCzEuD7BhjQgoyphn1K\n9jh+GuhTSdNxTkhbL279zFJsQxiC/DQfMzS7L48zGmqhqQdAC8Nph+CWixYMGPPW\nZN4DrSP2ExP5pQrYmLy4anqjKH9APCUODbfJVzxGY740Et/n6qJhv9Hvm6449hT/\nACOCWKPlkr2+7yp4bZU9HeU8qmrrkxOPjy7g/SpEcdHOFNOxd2wcj3GyfgLWxizY\nS5QV5vic/sftNORGhzhMB92NgJAecfnTjTyZSv8BtjQJGG0df8t/EO9/Qe9sk9Y2\nwKdv23VtRxqpIm10LRzkpSIMbm0nzkMySWOSRwDyTwIDAQABo0IwQDAOBgNVHQ8B\nAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU2oDTYavspTa+gqOP\noDM92JbYqE0wDQYJKoZIhvcNAQENBQADggIBALlcXhbUy4wfaczLuIG/EvhfgkSU\n1IFdCM/P0HKBbe3IFY4OLoM9KDt2Gc9b6b6gT77DYOis0jOmt692EzOu9Aql+1Oj\nRPtgROWRFxEiM7h1dY7Q87QIeUSNx0Udr9rb422PuvIXHZUFCpSot80SsSYsz2Ff\nr+kCNS/J+EcAo3a5WK4BkUquL2JeP18nyfN9ksHYDG72VGGT0QYsOS/x9vAWmGfK\nXQoIcJ+imKx5V37jK1eB7p2pLbYRRKVTGcPNDsLafAW3QeCWbrpTq8ZzNTKPmzm9\nriCmNMSspBLQzvXe09Y3lEXbYyFZEJIu5K0vmhtNe8HKCMeXnZBM1Fzo6nbC7vhH\n1BV05R0ge8KPVSJHSDi8AA22wfuCPBQdheu8G7kW54q8z/CWJkcnkR3UlylCx4Nk\nho4JE1mqj9pT2mYYC5ZFBLq7dJ/8kh1mMOFyqFO/aDujPbnnT8032O/4R0/TL9ra\nhtDK+WpVtnU9GPfVrx7YJNo+EbCN8j2iImuYCxiVPsqeQy5Do7OfBboShAR7MmTQ\nRsE1brR/CSzpiLDCH+dykb+WSbDyDbmMy3annkOGdY2zw7nSAkDgZQyFWc2OkVT0\neH6hCrfJlCzykz1eff4wJK/jmH1neaIs/CjVGEjkSN4k6nJrYlNrI0p/Tmk7ypFe\n1Pjdq/0gXAZlM1pZ\n-----END CERTIFICATE-----"
      CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_LOGPUSH_OWNERSHIP_TOKEN: ${{ secrets.CLOUDFLARE_LOGPUSH_OWNERSHIP_TOKEN }}
      CLOUDFLARE_API_USER_SERVICE_KEY: ${{ secrets.CLOUDFLARE_API_USER_SERVICE_KEY }}

    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - uses: actions/cache@v2.1.3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Pre-Sweeper
      run: go test ./cloudflare -v -sweep="1"

    - name: Run acceptance tests
      run: make testacc

    - name: Post-Sweeper
      if: ${{ always() }}
      run: go test ./cloudflare -v -sweep="1"
