name: Acceptance Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Vendor Replace Hack
      run: grep 'replace .* => \./' go.mod && go mod vendor; exit 0

    - name: Pre-Sweeper
      run: go test ./cloudflare -v -sweep="1"

    - name: Run acceptance tests
      run: make testacc

    - name: Post-Sweeper
      run: go test ./cloudflare -v -sweep="1"
