name: Lint
on: [push, pull_request]

jobs:
  # golangci:
  #   name: golangci-lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v2
  #       with:
  #         version: latest
  #         args: "--config .golintci.yml"
  #         only-new-issues: true # only show new issues in the PR, not all.

  tfproviderlint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - run: cd tools && go install github.com/bflad/tfproviderlint/cmd/tfproviderlintx
      - run: $(go env GOPATH)/bin/tfproviderlintx -R003=false -R011=false -R012=false -S006=false -S013=false -S014=false -S020=false -S022=false -S023=false -AT001=false -AT002=false -AT003=false -AT006=false -AT012=false -R013=false -XAT001=false -XR001=false -XR002=false -XR003=false -XR004=false -XR005=false -XS001=false -XS002=false ./cloudflare/
