name: Lint
on: [push, pull_request]

jobs:
  # golangci:
  #   name: golangci-lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v2
  #       with:
  #         version: latest
  #         args: "--config .golintci.yml"
  #         only-new-issues: true # only show new issues in the PR, not all.

  tfproviderlint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Run tfproviderlint
        uses: bflad/tfproviderlint-github-action@master
        with:
          args: -R003=false -R011=false -R012=false -S006=false -S013=false -S014=false -S020=false -S022=false -S023=false -AT001=false -AT002=false -AT003=false -AT006=false -AT012=false -R013=false ./cloudflare/
